// Generated by scripts/build_airports.py — do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace data::airports {

struct Airport {
  char icao[5];
  char iata[4];       // "" when the airport has no IATA code
  int32_t lat_e7;
  int32_t lon_e7;
  const char* city;   // ASCII-folded municipality, "" if unknown
};

constexpr size_t kAirportCount = 1259;

// Sorted by ICAO ident — binary-searchable.
extern const Airport kAirports[];

}  // namespace data::airports
