// Generated by scripts/build_large_airports.py — do not edit.
#pragma once

#include <cstddef>
#include <cstdint>

namespace data::large_airports {

enum class AirportType : uint8_t {
  kLarge = 0,
  kMedium = 1,
  kSmall = 2,
  kMilitary = 3,
};

struct Airport {
  char ident[5];
  int32_t lat_e7;
  int32_t lon_e7;
  AirportType type;
};

struct Runway {
  uint16_t airport_idx;
  int32_t le_lat_e7;
  int32_t le_lon_e7;
  int32_t he_lat_e7;
  int32_t he_lon_e7;
  uint16_t length_m;
};

constexpr size_t kAirportCount = 29205;
constexpr size_t kRunwayCount = 13292;

extern const Airport kAirports[];
extern const Runway kRunways[];

}  // namespace data::large_airports
