#!/usr/bin/env python3
"""Build the ICAO -> (city, IATA, position) table used to name route endpoints.

The route line on the aircraft tag comes from hexdb.io, which returns the two
airports as ICAO codes ("VIDP-EGLL"). This table turns each code into a
displayable city name (feeding the Italian-exonym lookup) and carries the
airport position so services::route can suppress a route whose endpoints are
nowhere near the aircraft (a reused / stale callsign).

Included (mirrors scripts/build_large_airports.py):
  * every ``large_airport`` worldwide
  * ``medium_airport`` / ``small_airport`` in LOCAL_COUNTRIES

Only airports with a 4-character ICAO ident and valid coordinates survive.
City names are transliterated to ASCII because the embedded VLW UI font only
ships the Latin basic glyph set.
"""

from __future__ import annotations

import csv
import io
import re
import unicodedata
import urllib.request
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUT_H = ROOT / "include" / "data" / "airports.h"
OUT_CPP = ROOT / "src" / "data" / "airports_data.cpp"

LOCAL_COUNTRIES = {"IT"}
LOCAL_TYPES = {"medium_airport", "small_airport"}

AIRPORTS_URL = (
    "https://raw.githubusercontent.com/davidmegginson/ourairports-data/main/"
    "airports.csv"
)

_TRANS = {
    "ø": "o", "Ø": "O", "ł": "l", "Ł": "L", "đ": "d", "Đ": "D", "ß": "ss",
    "æ": "ae", "Æ": "Ae", "œ": "oe", "Œ": "Oe", "ð": "d", "þ": "th", "ı": "i",
}


def to_ascii(s: str) -> str:
    """Latin letters lose diacritics; anything still non-ASCII is dropped."""
    out = []
    for ch in unicodedata.normalize("NFKD", s):
        if unicodedata.combining(ch):
            continue
        ch = _TRANS.get(ch, ch)
        if ord(ch) < 0x80:
            out.append(ch)
    return re.sub(r"\s+", " ", "".join(out)).strip()


def coord_e7(s: str | None) -> int | None:
    if not s or not s.strip():
        return None
    return int(round(float(s) * 1e7))


def c_str(s: str) -> str:
    return '"' + s.replace("\\", "\\\\").replace('"', '\\"') + '"'


def build_rows() -> list[tuple[str, str, int, int, str]]:
    with urllib.request.urlopen(AIRPORTS_URL, timeout=90) as resp:
        airports = list(csv.DictReader(io.StringIO(resp.read().decode("utf-8"))))

    rows: list[tuple[str, str, int, int, str]] = []
    for a in airports:
        atype = a.get("type")
        if atype == "large_airport":
            pass
        elif atype in LOCAL_TYPES and a.get("iso_country") in LOCAL_COUNTRIES:
            pass
        else:
            continue

        ident = (a.get("ident") or "").strip().upper()
        if len(ident) != 4 or not ident.isalnum():
            continue
        lat = coord_e7(a.get("latitude_deg"))
        lon = coord_e7(a.get("longitude_deg"))
        if lat is None or lon is None:
            continue

        iata = (a.get("iata_code") or "").strip().upper()
        if len(iata) != 3 or not iata.isalpha():
            iata = ""
        city = to_ascii(a.get("municipality") or "")
        rows.append((ident, iata, lat, lon, city))

    rows.sort(key=lambda r: r[0])
    return rows


def render_header(count: int) -> str:
    return "\n".join(
        [
            "// Generated by scripts/build_airports.py — do not edit.",
            "#pragma once",
            "",
            "#include <cstddef>",
            "#include <cstdint>",
            "",
            "namespace data::airports {",
            "",
            "struct Airport {",
            "  char icao[5];",
            "  char iata[4];       // \"\" when the airport has no IATA code",
            "  int32_t lat_e7;",
            "  int32_t lon_e7;",
            "  const char* city;   // ASCII-folded municipality, \"\" if unknown",
            "};",
            "",
            f"constexpr size_t kAirportCount = {count};",
            "",
            "// Sorted by ICAO ident — binary-searchable.",
            "extern const Airport kAirports[];",
            "",
            "}  // namespace data::airports",
            "",
        ]
    )


def render_cpp(rows: list[tuple[str, str, int, int, str]]) -> str:
    lines = [
        "// Generated by scripts/build_airports.py — do not edit.",
        '#include "data/airports.h"',
        "",
        "namespace data::airports {",
        "",
        "const Airport kAirports[] = {",
    ]
    for ident, iata, lat, lon, city in rows:
        lines.append(
            f'  {{"{ident}", "{iata}", {lat}, {lon}, {c_str(city)}}},'
        )
    lines += ["};", "", "}  // namespace data::airports", ""]
    return "\n".join(lines)


def main() -> int:
    rows = build_rows()
    OUT_H.write_text(render_header(len(rows)), encoding="utf-8")
    OUT_CPP.write_text(render_cpp(rows), encoding="utf-8")
    with_city = sum(1 for r in rows if r[4])
    print(
        f"wrote {OUT_H.name} + {OUT_CPP.name} "
        f"({len(rows)} airports, {with_city} with a city name)"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
